# NLP Workshop 6 (Hour 10 - 11)
# Transformers and spaCy

## 6.1 Introduction

In this workshop, you will learn about the latest hot topic in NLP, transformers, and how to use them with TensorFlow and spaCy.

First, you will learn about transformers and transfer learning. 

Second, you'll learn about the architecture details of the commonly used Transformer architecture – Bidirectional Encoder Representations from Transformers (BERT). 

You'll also learn how BERT Tokenizer and WordPiece algorithms work. 

Then you will learn how to quickly get started with pre-trained transformer models of the HuggingFace library. 

Next, you'll practice how to fine-tune HuggingFace Transformers with TensorFlow and Keras. 

Finally, you'll learn how spaCy v3.0 integrates transformer models as pre-trained pipelines.

These all techniques and tools you learnt will be used for the last workshop for building a Q&A Chatbot.  

In this workshop, we're going to cover the following main topics:
- Transformers and transfer learning
- Understanding BERT
- Transformers and TensorFlow
- Transformers and spaCy

## 6.2 Basic Requirements

To proceed with this workshop, make sure that you have installed <font color='blue'>Transformers</font>, <font color='blue'>Tensorflow</font> and <font color='blue'>spaCy</font> in your machine (if you are using your own PC/notebook computer instead of the campus JupyterHub Server).

To install these packages, using pip install commands:-
- pip install spacy
- pip install tensorflow (note: version 2.2 or above)
- pip install transformers

## 6.3 Transformers and Transfer Learning in a Nutshell

A milestone in NLP happened in 2017 with the release of the research paper <font color='blue'>Attention Is All You Need</font>, by Vaswani et al. (https://arxiv.org/abs/1706.03762), which introduced a brand-new machine learning idea and architecture – <font color='blue'>Transformers. 

<font color='blue'>Transformers</font> in NLP is a fresh idea that aims to solve sequential modeling tasks and targets some problems introduced by <font color='blue'>Long-Short-Term-Memory (LSTM)</font> architecture (recall LSTM architecture from previous workshop on Text Classification with spaCy). 
    
Here's how the paper explains how transformers work:

"The <font color='blue'>Transformer</font> is the first transduction model relying entirely on self-attention to compute representations of its input and output without using sequence-aligned RNNs or convolution."

<font color='blue'>Transduction</font> in this context means transforming input words to output words by transforming input words and sentences into vectors. Typically, a transformer is trained on a huge corpus such as Wiki or news. Then, in our downstream tasks, we use these vectors as they carry information regarding the word semantics, sentence structure, and sentence semantics (we'll see how to use the vectors precisely in our code in the Transformers and TensorFlow section).

We already explored the idea of pre-trained word vectors pervious workshop, Working with Word Vectors and Semantic Similarity. Word vectors such as Glove and FastText vectors are already trained on the Wikipedia corpus and we used them directly for our semantic similarity calculations. In this way, we imported information about word semantics from the Wiki corpus into our semantic similarity calculations. Importing knowledge from pre-trained word vectors or pre-trained statistical models is called <font color='blue'>Transfer Learning.

<font color='blue'>Transformers</font> offer thousands of pre-trained models to perform NLP tasks, such as text classification, text summarization, question answering, machine translation, and natural language generation in more than 100 languages. Transformers aim to make state-of-the-art NLP accessible to everyone.

The following screenshot shows a list of the <font color='blue'>Transformer</font> models provided by HuggingFace (we'll learn about HuggingFace Transformers in the HuggingFace Transformers section). Each model is named with a combination of the architecture name (<font color='blue'>BERT</font>, DistilBert, and so on), possibly the language code (en, de, multilingual, and similar, given on the left side of the following screenshot), and information regarding whether the model is cased or uncased (the model distinguishes between uppercase and lowercase characters).

Also, on the left-hand side of Fig. 1, we see the task names. Each model is labeled with a task name. We select a model that is suitable for our task, such as text classification or machine translation:
    
<img src="./Fig1.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 1. A list of HuggingFace Transformers (taken from the HuggingFace website)

## 6.4 Why Transformers?

To understand what's great about transformers, we'll first revisit LSTM architecture from last workshop: Text Classification with spaCy. 

In the previous workshop, we already stepped into the statistical modeling world with Keras and LSTM architecture. LSTMs are great for modeling text; however, they have certain major shortcomings:

- LSTM architecture sometimes has difficulties with learning long text. Statistical dependencies in a long text can be difficult to represent by an LSTM because, as the time steps pass, LSTM can forget some of the words that were processed at earlier time steps.

- The nature of LSTMs is sequential. We process one word at each time step. Obviously, parallelizing the learning process is not possible; we have to process sequentially. Not allowing parallelization creates a performance bottleneck.

<font color='blue'>Transformers </font> address these problems by not using recurrent layers at all. If we have a look at the following, the architecture looks completely different from an LSTM architecture. 

<font color='blue'>Transformer </font> architecture consists of two parts – an input encoder (called the Encoder) block on the left, and the output decoder (called the Decoder) block on the right. 

The following diagram is taken from this paper and exhibits the transformer architecture:

<img src="./Fig2.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 2. Transformer architecture (extracted from the paper entitled "Attention is All You Need")

The preceding architecture is invented for a machine translation task; hence, the input is a sequence of words from the source language, and the output is a sequence of words in the target language. The encoder generates a vector representation of the input words and passes them to the decoder (the word vector transfer is represented by the arrow from the encoder block in the direction of the decoder block). The decoder takes these input word vectors, transforms the output words into word vectors, and finally generates the probability of each output word (labeled in Fig. 2 as Output Probabilities).

Inside the encoder and decoder blocks, we see feedforward layers, which are basically a dense layer we used in the previous workshop, Text Classification with spaCy. The innovation transformers bring lies in the Multi-Head Attention block. This block creates a dense representation for each word by using a self-attention mechanism. The Self-attention mechanism relates each word in the input sentence to the other words in the input sentence. The word embedding of each word is calculated by taking a weighted average of the other words' embeddings. This way, the importance of each word in the input sentence is calculated, so the architecture focuses its attention on each input word in turn.

The following diagram is taken from the original paper and illustrates self-attention. The diagram illustrates how the input words on the left-hand side attend the input word "it" on the right-hand side. Darker colors mean more relevance, hence the words "the animal" are more related to "it" rather than the other words in this sentence. What does this mean? This means that the transformer can resolve what the pronoun "it" refers to precisely in this sentence, which is the phrase "the animal." This is a great accomplishment of transformers; they can resolve many semantic dependencies in a given sentence:

<img src="./Fig3.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 3. Illustration of the self-attention mechanism 

We have already seen that there is a variety of transformer architectures and, depending on the task, we use different types of transformers for different tasks, such as text classification and machine translation. 

In the rest of this workshop, we'll work with a very popular transformer architecture – <font color='blue'>BERT </font>. 

Let's see the <font color='blue'>BERT </font> architecture and how to use it in our NLP applications in the next section.

## 6.5 An Overview of BERT 


### 6.5.1 What is BERT?
In this section, we'll explore the most influential and commonly used Transformer model, BERT. BERT is introduced in Google's research paper here: https://arxiv.org/pdf/1810.04805.pdf.


What does BERT do exactly? To understand what BERT outputs, let's dissect the name:
- <font color='blue'>B</font>idirectional: Training on the text data is bi-directional, which means each input sentence is processed from left to right as well as from right to left.
- <font color='blue'>E</font>ncoder: An encoder encodes the input sentence.
- <font color='blue'>R</font>epresentations: A representation is a word vector.
- <font color='blue'>T</font>ransformers: The architecture is transformer-based.

<font color='blue'>BERT</font> is essentially a trained transformer encoder stack. Input into BERT is a sentence, and the output is a sequence of word vectors. The word vectors are contextual, which means that a word vector is assigned to a word based on the input sentence. In short, <font color='blue'>BERT</font> outputs contextual word representations.

We have already seen a number of issues that <font color='blue'>transformers</font> aim to solve in the previous section. 

Another problem that <font color='blue'>transformers</font> address concerns word vectors. In previous workshop: Working with Word Vectors and Semantic Similarity, we saw that word vectors are context-free; the word vector for a word is always the same independent of the sentence it is used in. 

The following diagram explains this problem:

<img src="./Fig4.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 4. Word vector for the word "bank"

Here, even though the word <font color='blue'>bank</font> has two completely different meanings in these two sentences, the word vectors are the same, because <font color='blue'>Glove</font> and <font color='blue'>FastText</font> are static. Each word has only one vector and vectors are saved to a file following training. Then, we download these pre-trained vectors and load them into our application.

On the contrary, <font color='blue'>BERT</font> word vectors are dynamic. <font color='blue'>BERT</font> can generate different word vectors for the same word depending on the input sentence. The following diagram shows the <font color='blue'>word vectors</font> generated by <font color='blue'>BERT</font>, in contrast to the <font color='blue'>word vector</font> in Fig. 4:

<img src="./Fig5.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 5. Two distinct word vectors generated by BERT for the same word, "bank," in two different contexts

How does <font color='blue'>BERT</font> generate these word vectors? In the next section, we'll explore the details of the <font color='blue'>BERT</font> architecture.

### 6.5.2 BERT Architecture

As has already been remarked in the previous section, <font color='blue'>BERT</font> is a transformer encoder stack, which means that several encoder layers are stacked on top of each other. The first layer initializes the word vectors randomly, and then each encoder layer transforms the output of the previous encoder layer. The paper introduces two model sizes for <font color='blue'>BERT</font>: <font color='blue'>BERT</font> Base and <font color='blue'>BERT</font> Large. The following diagram shows the <font color='blue'>BERT</font> architecture:

<img src="./Fig6.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 6. BERT Base and Large architectures, having 12 and 24 encoder layers, respectively


Both <font color='blue'>BERT</font> models have a huge number of encoder layers. <font color='blue'>BERT</font> Base has 12 encoder layers and <font color='blue'>BERT</font> Large has 24 encoder layers. The dimensions of the resulting word vectors are different too; <font color='blue'>BERT</font> Base generates word vectors of size 768 and <font color='blue'>BERT</font> Large generates word vectors of size 1024.

As we remarked in the previous section, <font color='blue'>BERT</font> outputs word vectors for each input word. The following diagram exhibits a high-level overview of <font color='blue'>BERT</font> inputs and outputs (discard the CLS token for now; you'll learn about it in the <font color='blue'>BERT</font> input format section):

<img src="./Fig7.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 7. BERT model input word and output word vectors


In the preceding diagram, we can see a high-level overview of <font color='blue'>BERT</font> inputs and outputs. 

Indeed, <font color='blue'>BERT</font> input has to be in a special format and includes some special tokens, such as CLS, in Fig.7. 

In the next section, you'll learn about the details of the <font color='blue'>BERT</font> input format.

### 6.5.3  BERT Input Format

We have covered <font color='blue'>BERT</font> architecture, so let's now understand how to generate the output vectors using <font color='blue'>BERT</font>. For this purpose, we'll get to know the <font color='blue'>BERT</font> input data format. 

The <font color='blue'>BERT</font> input format can represent a single sentence, as well as a pair of sentences (for tasks such as question answering and semantic similarity, we input two sentences to the model) in a single sequence of tokens.

<font color='blue'>BERT</font> works with a class of special tokens and a special tokenization algorithm called WordPiece. 

Let's get to know the special tokens first. The main special tokens are [CLS], [SEP], and [PAD]:

- The first special token of BERT is [CLS]. The first token of every input sequence has to be [CLS]. We use this token in classification tasks as an aggregate of the input sentence. We ignore this token in non-classification tasks.

- [SEP] means a sentence separator. If the input is a single sentence, we place this token at the end of the sentence. If the input is two sentences, then we use this token to separate two sentences. Hence, for a single sentence, the input looks like [CLS] sentence [SEP], and for two sentences, the input looks like [CLS] sentence1 [SEP] sentence2 [SEP].

- [PAD] is a special token meaning padding. Recall from the previous chapter that we use padding values to make sentences in our dataset of equal length. BERT receives sentences of a fixed length; hence, we pad the short sentences before feeding them to BERT. The maximum length of tokens we can feed to BERT is 512.

How about tokenizing the words? 

Recall from the previous section that we fed a sentence to our Keras model one word at a time. We tokenized our input sentences into words using the spaCy tokenizer. 

<font color='blue'>BERT</font> works slightly differently, <font color='blue'>BERT</font> uses WordPiece tokenization. A "word piece" is literally a piece of a word. 

The WordPiece algorithm breaks words down into several subwords. The idea is to break down complex/long tokens into simpler tokens. 

For example, the word playing is tokenized as play and ##ing. A ## character is placed before every word piece to indicate that this token is not a word from the language's vocabulary but that it's a word piece.

Let's take a look at some more examples:

playing   play, ##ing
played   play, ##ed
going    go, ##ing
vocabulary = [play,go, ##ing, ##ed]

This way, we represent the language vocabulary more compactly as <font color='blue'>WordPiece</font> groups common subwords. 

<font color='blue'>WordPiece</font> tokenization creates wonders on rare/unseen words, as these words are broken down into their subwords.

After tokenizing the input sentence and adding the special tokens, each token is converted to its ID. After that, as a final step, we feed the sequence of token IDs to <font color='blue'>BERT</font>.

To summarize, this is how we transform a sentence into <font color='blue'>BERT</font> input format:

<img src="./Fig8.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 8. Transforming an input sentence into BERT input format


<font color='blue'>BERT</font> Tokenizer has different methods for performing all the tasks described previously, but it also has an encoding method that combines these steps into a single step. We'll see how to use <font color='blue'>BERT</font> Tokenizer in detail in the <font color='blue'>Transformers</font> and <font color='blue'>TensorFlow</font> section. Before that, we'll learn about the algorithms that are used to train <font color='blue'>BERT</font>.

### 6.5.4 How to Train BERT?

<font color='blue'>BERT</font> is trained on a large unlabeled Wiki corpus and a huge book corpus. 

Creators of BERT stated the following in Google Research's <font color='blue'>BERT</font> GitHub repository, https://github.com/google-research/bert, as follows:

"We then train a large model (12-layer to 24-layer Transformer) on a large corpus (Wikipedia + BookCorpus) for a long time (1M update steps), and that's <font color='blue'>BERT</font>."

<font color='blue'>BERT</font> is trained with two training methods, masked language model (MLM) and next sentence prediction (NSP). Let's first go over the details of masked language modeling.

Language modeling is the task of predicting the next token given the sequence of previous tokens. 

For example, given the sequence of words Yesterday I visited, a language model can predict the next token as one of the tokens church, hospital, school, and so on. 

Masked language modeling is a bit different. In this approach, we mask a percentage of the tokens randomly by replacing them with a [MASK] token and expect MLM to predict the masked words.

The masked language model in <font color='blue'>BERT</font> is implemented as follows: First, 15 of the input tokens are chosen at random. Then, the following happens:
1. 80% of the tokens chosen are replaced with [MASK].
2. 10% of the tokens chosen are replaced with another token from the vocabulary.
3. The remaining 10% are left unchanged.

A training example sentence to LMM looks like the following:

[CLS] Yesterday I [MASK] my friend at [MASK] house [SEP]

Next, we will look into the details of the other algorithm, NSP.

As the name suggests, NSP is the task of predicting the next sentence given an input sentence. In this approach, we feed two sentences to <font color='blue'>BERT</font> and expect <font color='blue'>BERT</font> to predict the order of the sentences, more specifically, if the second sentence is the sentence following the first sentence.

Let's make an example input to NSP. We'll feed two sentences separated by the [SEP] token as input:

[CLS] A man robbed a [MASK] yesterday [MASK] 8 o'clock [SEP] He [MASK] the bank with 6 million dollars [SEP]

Label = IsNext

In this example, the second sentence can follow the first sentence; hence, the predicted label is IsNext. 

How about this example:

[CLS] Rabbits like to [MASK] carrots and [MASK] leaves [SEP] [MASK] Schwarzenegger is elected as the governor of [MASK] [SEP]

Label= NotNext

This example pair of sentences generate the NotNext label, as obviously they are not contextually or semantically related.

That's it! We have learned about <font color='blue'>BERT</font> architecture; we also learned the details of <font color='blue'>BERT</font> input data format and how <font color='blue'>BERT</font> is trained. 

Now, we're ready to dive into <font color='blue'>TensorFlow</font> code. 

In the next section, we'll see how to apply what we learned so far in our <font color='blue'>TensorFlow</font> code.

## 6.6 Transformers with TensorFlow

In this section, we'll dive into transformers code with TensorFlow. 

Pre-trained transformer models are provided to the developer community as open source by many organizations, including Google (https://github.com/google-research/bert), Facebook (https://github.com/pytorch/fairseq/blob/master/examples/language_model/README.md), and HuggingFace (https://github.com/huggingface/transformers). 

All the listed organizations offer pre-trained models and nice interfaces to integrate transformers into our Python code. 

The interfaces are compatible with either PyTorch or Tensorflow or both.

Throughout this chapter, we'll be using HuggingFace's pre-trained transformers and their TensorFlow interface to the transformer models. 

HuggingFace is an AI company with a focus on NLP and quite devoted to open source. 

In the next section, we'll take a closer look at what is available in HuggingFace Transformers.


### 6.6.1 HuggingFace Transformers


In the first section, we'll discover HuggingFace's pre-trained models, the TensorFlow interface for using these models, and HuggingFace model conventions in general. We saw in Fig. 1 that HuggingFace offers different sorts of models. Each model is dedicated to a task such as text classification, question answering, and sequence-to-sequence modeling.

The following diagram is taken from the HuggingFace documentation and shows details of the distilbert-base-uncased-distilled-squad model. In the documentation, first, the task is tagged (upper-left corner of the diagram; the Question Answering tag), followed by supported deep learning libraries (PyTorch, TensorFlow, TFLite, TFSavedModel for this model), the dataset it trained on (squad, in this instance), the model language (en for English), and the license and base model's name (DistilBERT in this case).

Some models are trained with similar algorithms, and so belong to the same model family. By way of an example, the DistilBERT family includes many models, such as distilbert-base-uncased and distilbert-multilingual-cased. Each model name also includes some information, such as casing (the model recognizes uppercase/lowercase differences) or the model language, such as en, de, or multilingual:

<img src="./Fig9.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 9. Documentation of the distilbert-base-uncased-distilled-squad model


We already explored BERT in detail in the previous section. HuggingFace documentation provides information about each model family and an individual model's API in detail. Fig. 10 shows a list of available models and a list of BERT model architecture variations:


<img src="./Fig10.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 10. List of the available models on the left-hand side, with a list of the BERT model variations on the right-hand side


The <font color='blue'>BERT</font> model has many variations for a variety of tasks, such as text classification, question answering, and next sentence prediction. 

Each of these models is obtained by placing some extra layers on top of the<font color='blue'>BERT</font> output. 

Recall from the previous section that the <font color='blue'>BERT</font> output is a sequence of word vectors for each word of the input sentence. 

For example, the BERTForSequenceClassification model is obtained by placing a dense layer (we covered dense layers in the previous chapter) on top of the BERT word vectors.

In the rest of this chapter, we'll explore how to use some of these architectures for our tasks as well as how to use <font color='blue'>BERT</font> word vectors with Keras. 

Before all of these tasks, we will start with the basic task of tokenization to prepare our input sentences. 

Let's see the tokenizer code in the next section.

### 6.6.2 Using the BERT Tokenizer

In the previous section, we already saw that BERT uses the WordPiece algorithm for tokenization. Every input word is broken down into subwords. 

Let's see how to prepare our input data with the HuggingFace library.

The following lines exhibit the basic usage of the tokenizer:

In [1]:
from transformers import BertTokenizer

btokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
sentence = "He lived characteristically idle and romantic."
sentence = "[CLS] " + sentence + " [SEP]"
tokens = btokenizer.tokenize(sentence)

/Users/ziho/opt/anaconda3/envs/nlpbook/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
tokens

['[CLS]',
 'he',
 'lived',
 'characteristic',
 '##ally',
 'idle',
 'and',
 'romantic',
 '.',
 '[SEP]']

In [3]:
ids = btokenizer.convert_tokens_to_ids(tokens)
ids

[101, 2002, 2973, 8281, 3973, 18373, 1998, 6298, 1012, 102]

<img src="./note.png" width = "" height = "" alt="note" align=left />

1. First, we imported BertTokenizer. Different models have different tokenizers; for instance, XLNet model's tokenizer is called XLNetTokenizer.

2. Second, we called the from_pretrained method on the tokenizer object and provided the model's name. Note that we don't need to download the pre-trained bert-base-uncased model manually; this method downloads the model by itself.

3. Then, we called the tokenize method. tokenize basically tokenizes the sentence by breaking all the words down into subwords.

4. We print tokens to examine the subwords. The words "he," "lived," "idle," and so on exist in Tokenizer's vocabulary, and so are kept as they are. "Characteristically" is a rare word, so does not exist in Tokenizer's vocabulary. Then, Tokenizer splits this word into the subwords "characteristic" and "##ally." Notice that "##ally" starts with the characters "##" to emphasize the fact that this is a piece of word.

5. After that, we convert tokens to their token IDs by calling convert_tokens_to_ids.

So, how about [CLS] and [SEP] tokens? 

In the previous section, we already saw that we have to add these two special tokens to the beginning and end of the input sentence. For the preceding code, we need to involve one more step and add our special tokens manually. Can we do all of these preprocessing steps in a single step, perhaps? 

The answer is yes; BERT provides a method called encode that does the following:
- Adds CLS and SEP tokens to the input sentence
- Tokenizes the sentence by breaking the tokens down into subwords
- Converts the tokens to their token IDs

To do so, we call the encode method directly on the input sentence as follows:

In [4]:
from transformers import BertTokenizer

btokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
sentence = "He lived characteristically idle and romantic."
ids = btokenizer.encode(sentence)
print(ids)

[101, 2002, 2973, 8281, 3973, 18373, 1998, 6298, 1012, 102]

<img src="./note.png" width = "" height = "" alt="note" align=left />

Note: <br>
This code segment outputs the token IDs in just a single step, instead of calling tokenize and convert_tokens_to_ids one after the other. The result is a Python list.

How about padding the sentence? 

We already saw in the previous section that all the input sentences in a dataset should be of equal length because <font color='blue'>BERT</font> cannot process variable-length sentences. Hence, we need to pad the short sentences to the length of the longest sentence available in the dataset by using the parameter "padding='longest'". 

Also, if we want to use a TensorFlow tensor instead of a plain list, we need to write some conversion code. The HuggingFace library provides encode_plus to make our life easier and combine all these steps into one method as follows:

In [5]:
from transformers import BertTokenizer

btokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
sentence = "He lived characteristically idle and romantic."

encoded = btokenizer.encode_plus(
        text=sentence,
        add_special_tokens=True,
        padding='longest',
        return_tensors="tf"
)

token_ids = encoded["input_ids"]

print(token_ids)

tf.Tensor([[  101  2002  2973  8281  3973 18373  1998  6298  1012   102]], shape=(1, 10), dtype=int32)

2022-06-21 22:01:30.099864: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Here, we called encode_plus on our input sentence directly. Our sentence is now padded to a length of 10, while the special tokens [CLS] and [SEP] are also added to the sentence. The output is directly a TensorFlow tensor, including the token IDs.

To check the parameter list of encode_plus(), try the following:

In [6]:
btokenizer.encode_plus?

As we can see, <font color='blue'>BERT</font> Tokenizer provides several methods on input sentences. Preparing data is not so straightforward, but you'll get used to it by practicing. We always encourage you to try out the code examples with your own text.

Now, we're ready to process the transformed input sentences. Let's go ahead and provide our input sentences to the <font color='blue'>BERT</font> model to obtain <font color='blue'>BERT</font> word vectors.

### 6.6.3 Word Vectors in BERT

In this section, we'll examine the output of the BERT model. As we stated in the previous section, the output of the BERT model is a sequence of word vectors, one vector per input word. BERT has a special output format and, in this section, we'll examine BERT outputs in detail.

Let's see the code first:

In [7]:
from transformers import BertTokenizer, TFBertModel

btokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bmodel = TFBertModel.from_pretrained("bert-base-uncased")

sentence = "He was idle."

encoded = btokenizer.encode_plus(
        text=sentence,
        add_special_tokens=True,
        padding='longest', 
        max_length=10,
        return_attention_mask=True,
        return_tensors="tf"
)

inputs = encoded["input_ids"]

outputs = bmodel(inputs)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.

<img src="./note.png" width = "" height = "" alt="note" align=left />

Note: <br>
- This code is very similar to the code from the previous section. Here, we also imported TFBertModel. 
- After that, we initialized out BERT model with the pre-trained model, bert-base-uncased. 
- Then, we transformed our input sentence to BERT input format with encode_plus and captured the result, tf.tensor, in the input variable. 
- We fed our sentence to the BERT model and captured this output with the outputs variable. What's inside the outputs variable then?

The output of the BERT model is a tuple of two elements. Let's print the shapes of the output pair:

In [8]:
print(outputs[0].shape)

(1, 6, 768)

In [9]:
print(outputs[1].shape)

(1, 768)

<img src="./note.png" width = "" height = "" alt="note" align=left />

Note: <br>
1. The first element of the output is the shape (batch size, sequence length, hidden size). We fed only one sentence, hence the batch size here is 1 (the batch size is how many sentences we feed to the model at once). The sequence length here is 10 because we fed max_length=10 to the tokenizer and padded our sentence to a length of 10. hidden_size is a parameter of BERT. In the BERT Architecture section, we already remarked that BERT's hidden layer size is 768, and so produces word vectors with a dimension of 768. So, the first output element contains 768-dimensional vectors per word, hence it contains 10 words x 768-dimensional vectors.

2. The second output is only one vector of 768-dimension. This vector is basically the word embedding of the [CLS] token. Recall from the BERT input format section that the [CLS] token is an aggregate of the whole sentence. You can think of [CLS] token's embedding as the pooled version of embeddings of all the words in the sentence. The shape of the second element of the output tuple is always (batch size, hidden_size). Basically, we collect the [CLS] token's embedding per input sentence.

Great! We extracted the BERT embeddings. Next, we'll use these embeddings to train our text classification model with TensorFlow and tf.keras.

## 6.7 Revisit Text Classification now using BERT

In this section, we'll train a binary text classifier with <font color='blue'>BERT</font> and <font color='blue'>tf.keras</font>. 

We'll reuse some of the code from the previous chapter, but this time the code will be much shorter because we'll replace the embedding and <font color='blue'>LSTM</font> layers with <font color='blue'>BERT</font>. 

Data can be found in our Data directory namely <font color='blue'>spam.csv</font>.

### 6.7.1 Data Preparation

Before we create to Text Classification model using BERT, let's prepare the data first just like we have learnt in the previous workshop:

1. Import the related modules:

In [29]:
import pandas as pd
import numpy as np
import tensorflow
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model

2. Read the spam.csv datafile.

In [30]:
data=pd.read_csv("emails.csv",encoding='ISO-8859-1')
data.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [37]:
data=data.dropna()                                                           
data=data.reset_index(drop=True) 
data.columns = ['text','label']
data.head()

                                                text  label
0  Subject: naturally irresistible your corporate...      1
1  Subject: the stock trading gunslinger  fanny i...      1
2  Subject: unbelievable new homes made easy  im ...      1
3  Subject: 4 color printing special  request add...      1
4  Subject: do not have money , get software cds ...      1

### 6.7.2 Get Start Now ...

First, let's get started by importing the BERT models and tokenizer:

In [38]:
from transformers import BertTokenizer, TFBertModel, BertConfig, TFBertForSequenceClassification
bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
bmodel = TFBertModel.from_pretrained("bert-base-uncased")

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.

<img src="./note.png" width = "" height = "" alt="note" align=left />

Note: 
1. We have imported the BertTokenizer tokenizer and the BERT model, TFBertModel. 
2. We initialized both the tokenizer and the BERT model with the pre-trained bert-base-uncased model. Notice that the model's name starts with TF – the names of all of the HuggingFace pre-trained models for TensorFlow start with TF. Please pay attention to this detail when you want to play with other transformer models in the future.

Now, we're ready to process the input data with BertTokenizer:

In [39]:
data.head()

                                                text  label
0  Subject: naturally irresistible your corporate...      1
1  Subject: the stock trading gunslinger  fanny i...      1
2  Subject: unbelievable new homes made easy  im ...      1
3  Subject: 4 color printing special  request add...      1
4  Subject: do not have money , get software cds ...      1

Double check the databank see whether data are there:

In [40]:
sentences=data['text']
labels=data['label']
len(sentences),len(labels)

(5728, 5728)

In [41]:
input_ids=[]
attention_masks=[]

for sent in sentences:
    bert_inp=bert_tokenizer.encode_plus(sent,add_special_tokens = True,max_length =64,pad_to_max_length = True,return_attention_mask = True)
    input_ids.append(bert_inp['input_ids'])
    attention_masks.append(bert_inp['attention_mask'])

input_ids=np.asarray(input_ids)
attention_masks=np.array(attention_masks)
labels=np.array(labels)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/Users/ziho/opt/anaconda3/envs/nlpbook/lib/python3.8/site-packages/transformers/tokenization_utils_base.py:2285: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(

<img src="./note.png" width = "" height = "" alt="note" align=left />

Note: 
As we saw in the Using the BERT tokenizer section, this code segment will generate token IDs for each input sentence of the dataset and append them to a list. Labels are the list of class labels and consist of 0 and 1s. Then we convert the Python lists, input_ids, and labels to numpy arrays to feed them to our Keras model.

Finally, we define our Keras model by means of the following lines:

In [42]:
inputs = Input(shape=(64,), dtype="int32")
bert = bmodel(inputs)
bert = bert[1]
outputs = Dense(units=1, activation="sigmoid")(bert)
model = Model(inputs, outputs)

adam = tensorflow.keras.optimizers.Adam(learning_rate=2e-5,epsilon=1e-08)
model.compile(loss="binary_crossentropy", metrics=["accuracy"], optimizer=adam)

In [20]:
model.fit?

In [21]:
history=model.fit(input_ids,labels,batch_size=1,epochs=1)

5572/5572 [==============================] - 3478s 623ms/step - loss: 0.0851 - accuracy: 0.9770

Check the Model Summary:

In [22]:
bmodel.summary()

Model: "tf_bert_model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 bert (TFBertMainLayer)      multiple                  109482240

=================================================================
Total params: 109,482,240
Trainable params: 109,482,240
Non-trainable params: 0
_________________________________________________________________

That's it! We defined our BERT-based text classifier in only 8 lines of code! 
1. First, we defined the input layer, which inputs the sentences to our model. The shape is (64,) because each input sentence is 64 tokens in length. We padded each sentence to the length of 64 tokens when we called the encode_plus method.
2. Next, we fed the input sentences to the BERT model.
3. At the third line, we extracted the second output of the BERT output. Recall from the previous section that the BERT model's output is a tuple. The first element of the output tuple is a sequence of word vectors, and the second element is a single vector that represents the whole sentence, called pooled output vector. bert[1] extracts the pooled output vector; this is a vector of shape (1, 768).
4. Next, we squashed the pooled output vector to a vector of shape 1 by a sigmoid function, which is the class label.
5. We defined our Keras model with the inputs and outputs.
6. Comple the model.
7. Fit the Keras model.

Here, the BERT model takes only one line but can transfer the enormous knowledge of the Wiki corpus to your model. At the end of the training, this model obtains an accuracy of 0.96. We usually fit the model for one epoch due to fact that BERT overfits easily even on a moderate size corpus.

The rest of the code handles compiling and fitting the Keras model. Note that BERT has huge memory requirements also. 

You can see how much RAM is required from Google Research's GitHub link: https://github.com/google-research/bert#out-of-memory-issues.

Our training code runs in my local machine for around 1 hour, while bigger datasets can take more time even though it's just one epoch.

In this section, we learned how to train a Keras model with BERT from scratch. Now, we'll switch to an easier task. We'll explore how to use a pre-trained transformer pipeline. Let's move on to the next section for the details.

## 6.8 Using Transformer Pipeline

The HuggingFace Transformers library provides pipelines to help developers benefit from transformer code immediately without any custom training. A pipeline is a tokenizer and a pre-trained model combined.

HuggingFace provides a variety of models for a variety of NLP tasks. Here are some tasks that HuggingFace pipelines offer:
- Sentiment analysis
- Question answering
- Text summarization
- Translation

You can see the full list of tasks at the Huggingface documentation: https://huggingface.co/transformers/task_summary.html. 

In this section, we'll explore the pipelines for sentiment analysis and question answering (the use of pipelines with other tasks is similar).

### 6.8.1 Transformer Pipeline for Sentiment Analysis

Let's go through some examples. We'll start with sentiment analysis:

In [24]:
from transformers import pipeline

nlp = pipeline("sentiment-analysis")


sent1 = "I hate I hate being a worker in the desert."
sent2 = "I like you who are beautiful and kind."

result1 = nlp(sent1)
result2 = nlp(sent2)

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)
Downloading: 100%|██████████████████████████████| 629/629 [00:00<00:00, 112kB/s]
Downloading: 100%|███████████████████████████| 256M/256M [00:18<00:00, 14.8MB/s]
Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_93']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Downloading: 100%|███████████████████████████| 48.0/48.0 [00:00<00:00, 27.9kB/s]
Downloading: 100%|███████████████████████████| 226k/226k [00:12<00:00, 17.9kB/s]

In the preceding code snippet, we took the following steps:

First, we imported the pipeline function from the transformers library. 

This function creates pipeline objects with the task name given as a parameter. Hence, we created our sentiment analysis pipeline object, nlp, by calling this function on the second line.

Next, we define two example sentences with negative and positive sentiment, respectively.
Then we feed these sentences to the pipeline object, nlp.

Check the outputs:

In [25]:
result1

[{'label': 'NEGATIVE', 'score': 0.9984997510910034}]

In [26]:
result2

[{'label': 'POSITIVE', 'score': 0.9998718500137329}]

### 6.8.2 Transformer Pipeline for QA System

This worked great! 

Next, we'll play with question answering. 

Let's see the code:

In [27]:
from transformers import pipeline

nlp = pipeline("question-answering")

res = nlp({
    'question': 'What is the name of this book ?',
    'context': "I'll publish my new book Natural Language Processing soon."
})

print(res)

No model was supplied, defaulted to distilbert-base-cased-distilled-squad (https://huggingface.co/distilbert-base-cased-distilled-squad)
Downloading: 100%|██████████████████████████████| 473/473 [00:00<00:00, 324kB/s]
Downloading: 100%|███████████████████████████| 249M/249M [00:07<00:00, 32.8MB/s]
Some layers from the model checkpoint at distilbert-base-cased-distilled-squad were not used when initializing TFDistilBertForQuestionAnswering: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForQuestionAnswering were not initialized from the model checkpoint at distilbert-base-cased-distilled-squad and are newly initialized: ['dropout_113']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Downloading: 100%|███████████████████████████| 29.0/29.0 [00:00<00:00, 20.1kB/s]
Downloading: 100%|███████████████████████████| 208k/208k [00:14<00:00, 14.9kB/s]
Downloading: 100%|███████████████████████████| 426k/426k [00:25<00:00, 17.3kB/s]

{'score': 0.9857437014579773, 'start': 25, 'end': 52, 'answer': 'Natural Language Processing'}

### <img src="./note.png" width = "" height = "" alt="note" align=left />

Note:
- Again, we imported the pipeline function and used it to create a pipeline object, nlp. - In question-answering tasks, we need to provide a context (the same background information for the model to work on) to the model as well as our question. 
- We asked the model about the name of this book after giving the information that our new publication will be out soon. 
- The answer is Natural Language Processing; the transformer worked wonders on this pair! 
- We encourage you to try out your own examples.

We have completed our exploration of HuggingFace transformers. Now, we will move on to our final section of this chapter and see what spaCy offers us as regards transformers.

<img src="./workshop.png" width = "" height = "" alt="note" align=left />

### Workshop 6.1  Revisit the Sentiment Analysis

In previous workshop, we have done the Sentiment Analysis. In this workshop, we revisit the Sentiment Analysis using Transformer Technology. 

1. You can either use the previous workshop databank or choose another databank to import the databank for Sentiment Analysis. 
2. Try to implement Sentiment Analysis using the previous and the Transformer technology learnt in this workshop. 
3. Compare their performances (MUST) and do some useful analysis (bonus).

## 6.9 Transformers and spaCy

spaCy v3.0 was released with great new features and components. The most exciting new feature is undoubtedly transformer-based pipelines. 

The new transformer-based pipelines bring spaCy's accuracy to the state of the art. Integrating transformers into the spaCy NLP pipeline introduced one more pipeline component called Transformer. 

This component allows us to use all HuggingFace models with spaCy pipelines. This is what the spaCy NLP pipeline looks like without transformers:

<img src="./Fig11.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 11. Vector-based spaCy pipeline components


With the release of v3.0, v2 style spaCy models are still supported and transformer-based models are introduced. A transformer-based pipeline component looks like the following:

<img src="./Fig12.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 12. Transformed-based spaCy pipeline components


For each supported language, transformer-based models and v2 style models are listed under the Models page of the documentation (English for an example: https://spacy.io/models/en). 

Transformer-based models can have different size and pipeline components, just like v2 style models. 

Also, each model has corpus and genre information as well, just like the v2 style models. 

Here is an example of an English transformer-based language model from the Models page:

<img src="./Fig13.jpg" width = "" height = "" alt="Fig1" align=center />
Fig 13. spaCy English transformer-based language models


As we see from the preceding screenshot, the first pipeline component is a transformer. The transformer component generates the word representations and deals with the WordPiece algorithm to tokenize words into subwords. The word vectors are fed to the rest of the pipeline.

Downloading, loading, and using transformer-based models are identical to v2 style models. 

Currently, English has two pre-trained transformer-based models, en_core_web_trf and en_core_web_lg. Let's get started by downloading the en_core_web_trf model:

python3 -m spacy download en_core_web_trf

To get start, first, we import the spacy module and the transformer based model:

In [ ]:
import spacy
import torch
import spacy_transformers
nlp = spacy.load("en_core_web_trf")

After loading our model and initializing the pipeline, we can use this model in the same way we used v2 style models:

In [ ]:
doc = nlp("I visited my friend Betty at her house.")
doc.ents

In [ ]:
for word in doc:
    print(word.pos_, word.lemma_)

So far so good, but what's new then? 

Let's examine some features that come from the transformer component. 

We can access the features related to the transformer component via <font color='blue'>doc._.trf_data.trf_data</font>, which contains the word pieces, input <font color='blue'>ids</font>, and vectors that are generated by the transformer. 

Let's examine the features one by one:

In [ ]:
doc = nlp("It went there unwillingly.")

In [ ]:
doc._.trf_data.wordpieces

In the preceding output, we see five elements: word pieces, input IDs, attention masks, lengths, and token type IDs. 

Word pieces are the subwords that are generated by the WordPiece algorithm. The word pieces of this sentence are as follows:

<s>
It
Gwent
Gthere
Gunw
Ill
ingly
.
</s>

Here, first and last tokens are special tokens and are used in the sentence at the beginning and end. The word unwillingly is divided into three subwords – unw, ill, and ingly. The G character is used to mark the word boundaries. The tokens without G are subwords, such as ill and ingly in the preceding word piece list (with the exception of the first word in the sentence, the first word of the sentence is marked by <'s'>).

Next, we have to take a look at input_ids. Input IDs have the same meaning as the input IDs we introduced in the Using the BERT tokenizer section. These are basically the subword IDs assigned by the transformer's tokenizer.

The attention mask is a list of 0s and 1s for pointing the transformer to those tokens it should pay attention to. 0 corresponds to PAD tokens, while all the other tokens should have a corresponding 1.

lengths is the length of the sentence after breaking it down into subwords. Here, it's 9 obviously, but notice that len(doc) outputs 5, while spaCy always operates on linguistic words.

token_type_ids are used by transformer tokenizers to mark the sentence boundaries for two sentence input tasks, such as question and answering. Here, we provide only one text, hence this feature is not applicable.

We can see that the token vectors generated by the transformer, doc._.trf_data.tensors, contain the output of the transformer, a sequence of word vectors per word, and the pooled output vector (we introduced these concepts in the Obtaining BERT word vectors section. If you need to refresh your memory, please refer to this section):

In [ ]:
doc._.trf_data.tensors[0].shape

In [ ]:
doc._.trf_data.tensors[1].shape

The first element of the tuple is the vectors for the tokens. Each vector is 768-dimensional; hence 9 words produce 9 x 768-dimensional vectors. The second element of the tuple is the pooled output vector, which is an aggregate representation for the input sentence, and so is of the shape 1x768.

This concludes our exploration of spaCy transformer-based pipelines. Once again, we saw that spaCy provides user-friendly API and packaging, even for complicated models such as transformers. Transformer integration is yet another great reason to use spaCy for NLP.

## 6.10 Summary

You have completed an exhaustive chapter about a very hot topic in NLP. Congratulations! In this chapter, you started by learning what sort of models transformers are and what transfer learning is. Then, you learned about the commonly used Transformer architecture, BERT. You learned the architecture details and the specific input format, as well as the BERT Tokenizer and WordPiece algorithm.

Next, you became familiar with BERT code by using the popular HuggingFace Transformers library. You practiced fine-tuning BERT on a custom dataset for a sentiment analysis task with TensorFlow and Keras. You also practiced using pre-trained HuggingFace pipelines for a variety of NLP tasks, such as text classification and question answering. Finally, you explored the spaCy and Transformers integration of the new spaCy release, spaCy v3.0.

By the end of this workshop, you had completed the statistical NLP sections of this book. Now you're ready to put everything you learned together to build a modern NLP pipeline. Let's move on to the next chapter and see how we use our new statistical skills!